stages:
  - build
build-windows:
  tags:
    - msvc142
  variables:
    GIT_STRATEGY: fetch
    TRIPLET: "x64-windows"
    #PACKAGES: "boost curl[ssl,openssl,winssl,non-http,ssh,brotli] curlpp jsoncpp libgit2 libpq libpqxx soci[odbc,postgresql,sqlite3]" # libmariadb thrift grpc wt 7zip capnproto cppcms cppcodec cpprestsdk freetds[openssl] google-cloud-cpp icu imgui json-spirit nana platform-folders podofo qwt x-plane pugixml qt5
    PACKAGES: "jsoncpp zlib"
  stage: build
  before_script:
    - 'net use J: \\FILESRV\Shared /user:jenkins_user 3Edcft67; echo ok'
    - 'subst Q: (Get-Location); echo ok'
  script:
    - Invoke-BatchFile "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\Common7\Tools\VsMSBuildCmd.bat"
    - $physicalBuildPath = Get-Location
    #- 'subst Q: $physicalBuildPath; echo ok'
    - Set-Location Q:\
    - .\bootstrap-vcpkg.bat -disableMetrics
    - $Env:VCPKG_DEFAULT_TRIPLET=$TRIPLET
    - .\vcpkg.exe upgrade --no-dry-run
    - $pckgs = $PACKAGES
    - Write-Output $pckgs
    - '.\vcpkg.exe install $pckgs --recurse'
    - Set-Location $physicalBuildPath
  after_script:
    - '.\vcpkg.exe export $PACKAGES --ifw --output=vcpkg-$TRIPLET'
    - Copy-Item "vcpkg-$TRIPLET-ifw-installer.exe" -Destination "J:\vcpkg" -Force
    - 'net use /delete J:'
    - 'subst /d Q:'

  cache:
    key: vcpkg_msvc142_$TRIPLET
    paths:
    - downloads
    - installed
  after_script:
    - 'subst /d Q:'
  except:
    - tags


#build-linux:
#  tags:
#    - gcc
#  variables:
#    GIT_STRATEGY: fetch
#    GIT_DEPTH: 1

#  stage: build
#  script:
#  - scl enable sclo-git212 bash
#  - scl enable devtoolset-7 bash
#  - ./bootstrap-vcpkg.sh
#  - export VCPKG_DEFAULT_TRIPLET="x64-linux"
#  - ./vcpkg install curl[ssl,winssl] curlpp jsoncpp libgit2 libpq libpqxx openssl-windows openssl soci[odbc,postgresql,sqlite3] libmariadb thrift grpc wt
#  cache:
#    key: vcpkg_gcc_x64-linux_dynamic
#    paths:
#    - downloads
#    - installed
#  after_script:
#  except:
#    - tags
